### ISSUE TITLE
vue使用md插件 @wandeditor/plugin-md/dist/index.js文件出错

### ISSUE THREAD

**Issue by 1034148617** [wangeditor-team/wangEditor-plugin-md#1]
在vue里使用了wangeditor和md插件，提示index.js文件有错，找不到wangEditor，并且通过npm下载不了wangEditor
我将index.js文件里的wangEditor替换成了@wangeditor/editor解决，但是每次使用npm会覆盖我的更改

**Comment by wangfupeng1988** [comment]
正在解决这个问题，稍等

**Comment by wangfupeng1988** [comment]
已修改，升级最新的 `@wangeditor/plugin-md` 试试
