### ISSUE TITLE
如何在react项目中使用？

### ISSUE THREAD

**Issue by doYbest** [wangeditor-team/wangEditor-plugin-md#6]
是直接在wangeditor组件中加上插件文档的三行吗？
![image](https://user-images.githubusercontent.com/80409408/180596071-c31eb035-93a2-4a2a-8e23-9962a445a157.png)
还是需要额外封装？

**Comment by wangfupeng1988** [comment]
不需要，就这样用

**Comment by doYbest** [comment]
> 不需要，就这样用

![image](https://user-images.githubusercontent.com/80409408/180600413-0cea0ed8-f447-4c8d-afaf-e37873449818.png)
我是按照文档的demo加上了插件后在网页上并没有markdown的效果
![image](https://user-images.githubusercontent.com/80409408/180600476-492c9120-919d-472f-bcce-1c736ef744cf.png)
请问这是什么问题？
@wangfupeng1988

**Comment by wangfupeng1988** [comment]
输入 `##` 之后，要敲一下空格键
