### ISSUE TITLE
react引入插件问题

### ISSUE THREAD

**Issue by doYbest** [wangeditor-team/wangEditor-plugin-md#7]
我是按照文档的react的demo加上了插件后在网页上并没有markdown的效果
![image](https://user-images.githubusercontent.com/80409408/180601443-60b33e43-c76c-418d-9cf2-aa182c69ee3f.png)
![image](https://user-images.githubusercontent.com/80409408/180601456-63e423f7-d7df-4117-8787-2cb0cfeef491.png)

在网上看了很久没有找到解决的方法，请问这是什么问题？
@wangfupeng1988

**Comment by wangfupeng1988** [comment]
和 https://github.com/wangeditor-team/wangEditor-plugin-md/issues/6 重复了
